server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: config-server
          uri: https://github.com/ezequielchepe/microservicios-test
          search-paths:  config-data
  application:         
    name:  config-service